/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package array.contoh;

import java.awt.Dimension;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishom
 */

public class Buku_Tamu extends javax.swing.JFrame {
    //deklarasi variabel model
    DefaultTableModel model;
    
    /**
     * konstruktor
     */
    public Buku_Tamu() {
        //method untuk inisialisasi form
        initComponents();
        
        //atur model tabel
        aturTabel();
    }
    
    /**
     * method untuk mengatur model tabel
     */
    private void aturTabel(){
        //mendefinisikan kolom pada JTable
        Object[] header = {"No","Tanggal","Nama Lengkap","Jenis Kelamin","Kantor/Instansi","Keperluan"};
        //instansiasi model untuk sebuah tabel
        model = new DefaultTableModel(header, 0);
        //atur model JTable menggunakan model yang telah kita
        //definisikan di atas.
        tabelTamu.setModel(model); 
        //tinggi setiap baris adalah 25px
        tabelTamu.setRowHeight(25);        
        //spasi setiap cell adalah 10
        tabelTamu.setIntercellSpacing(new Dimension(10,1));        
        //kolom pertama (nomor) ukuran panjang kolom fix=50px
        tabelTamu.getColumnModel().getColumn(0).setMinWidth(50);
        tabelTamu.getColumnModel().getColumn(0).setMaxWidth(50);
        //kolom kedua (tanggal) ukuran panjang kolom fix=100px
        tabelTamu.getColumnModel().getColumn(1).setMinWidth(100);
        tabelTamu.getColumnModel().getColumn(1).setMaxWidth(100);
        //kolom keempat (jenis kelamin) ukuran panjang kolom fix=100px
        tabelTamu.getColumnModel().getColumn(3).setMinWidth(100);
        tabelTamu.getColumnModel().getColumn(3).setMaxWidth(100);        
        //agar kolom terakhir pada tabel bisa auto resize
        tabelTamu.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
    }
    
    private String tanggal(){
        //instansiasi kelas Date
        Date date = new Date();
        //atur format tanggal yang dinginkan
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        //return value = tanggal hari ini dengan format "hari/bulan/tahun"
        return sdf.format(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        rbL = new javax.swing.JRadioButton();
        rbP = new javax.swing.JRadioButton();
        txtKantor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKeperluan = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTamu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buku Tamu");

        jPanel1.setPreferredSize(new java.awt.Dimension(483, 230));

        buttonGroup1.add(rbL);
        rbL.setSelected(true);
        rbL.setText("Laki-Laki");

        buttonGroup1.add(rbP);
        rbP.setText("Perempuan");

        txtKeperluan.setColumns(20);
        txtKeperluan.setRows(5);
        jScrollPane2.setViewportView(txtKeperluan);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nama Lengkap");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Jenis Kelamin");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Kantor/Instansi");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tujuan/Keperluan");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbL)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbP))
                                .addComponent(txtNama)
                                .addComponent(txtKantor, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbL)
                    .addComponent(rbP)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKantor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tabelTamu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTamu);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(521, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        //ambil teks dalam komponen "txtNama" kemudian simpan dalam variabel "nama"
        String nama = txtNama.getText();
        //operator ternary
        //jika komponen "rbL" dipilih, maka jenis kelamin=Laki-Laki
        //selain itu, maka jenis kelamin=Perempuan
        String jenis_kelamin = rbL.isSelected()?"Laki-Laki":"Perempuan";
        //ambil teks dalam komponen "txtKantor" kemudian simpan dalam variabel "kantor"
        String kantor = txtKantor.getText();
        //ambil teks dalam komponen "txtKeperluan" kemudian simpan dalam variabel "keperluan"
        String keperluan = txtKeperluan.getText();
        //pengecekan
        //jika variabel "nama" tidak ada isinya atau kosong
        if(nama.isEmpty()){
            //taampilkan pesan "Nama lengkap harus diisi"
            JOptionPane.showMessageDialog(this, "Nama lengkap harus diisi!");
            //setelah itu, letakkan "caret cursor" pada komponen "txtNama"
            txtNama.requestFocus();            
            
        //jika variabel "kantor" tidak ada isinya atau kosong
        }else if(kantor.isEmpty()){
            //taampilkan pesan "Kantor/Instansi harus diisi!"
            JOptionPane.showMessageDialog(this, "Kantor/Instansi harus diisi!");
            //setelah itu, letakkan "caret cursor" pada komponen "txtKantor"
            txtKantor.requestFocus();
            
        //jika variabel "keperluan" tidak ada isinya atau kosong
        }else if(keperluan.isEmpty()){
            //taampilkan pesan "Keperluan harus diisi!"
            JOptionPane.showMessageDialog(this, "Keperluan harus diisi!");
            //setelah itu, letakkan "caret cursor" pada komponen "txtKeperluan"
            txtKeperluan.requestFocus();
            
        //jika data telah terisi dengan lengkap, maka simpan data ke dalam tabel
        }else {
            //untuk membuat nomor urut = jumlah baris dalam tabel + 1
            int nomor = tabelTamu.getRowCount()+1;
            //buat array object dari data
            Object[] data = {nomor,tanggal(),nama,jenis_kelamin,kantor,keperluan};
            //menambahkan baris data ke dalam tabel
            model.addRow(data); 
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            //mengatur tampilan aplikasi agar menyesuaikan look sistem operasi
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); 
        } catch (ClassNotFoundException | IllegalAccessException | 
                InstantiationException | UnsupportedLookAndFeelException e) {
        }
        java.awt.EventQueue.invokeLater(() -> {
            //instansiasi kelas Buku_Tamu
            Buku_Tamu bt = new Buku_Tamu();
            //atur agar window langsung maximize ketika dibuka
            bt.setExtendedState(Frame.MAXIMIZED_BOTH); 
            //tampilkan window
            bt.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbL;
    private javax.swing.JRadioButton rbP;
    private javax.swing.JTable tabelTamu;
    private javax.swing.JTextField txtKantor;
    private javax.swing.JTextArea txtKeperluan;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
